# Auto-generated by scripts/build-aur-packages.sh. Do not edit manually.
pkgname=${AUR_PKGNAME}
pkgver=${AUR_PKGVER}
pkgrel=${AUR_PKGREL}
pkgdesc="Binary wrapper for ${AUR_BASENAME} from Gundu Labs"
arch=${AUR_ARCH}
url="${AUR_URL}"
license=('custom')
depends=${AUR_DEPENDS}
source=("${AUR_FILE}::${AUR_SOURCE_URL}")
sha256sums=('${AUR_SHA256}')

package() {
  bsdtar -xpf "$srcdir/${AUR_FILE}" -C "$pkgdir"
  find "$pkgdir" -maxdepth 1 -type f -name '.*' -delete
}
